version: "3.8"

services:
  nginx:
    image: "nginx:stable-alpine"
    ports:
      - "8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src:/var/www/laravel

  php:
    build:
      context: dockerfiles
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/laravel

  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    env_file:
      - env/postgres.env

  composer:
    build:
      context: dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/laravel
    environment:
      - COMPOSER_MEMORY_LIMIT=-1
      - COMPOSER_PROCESS_TIMEOUT=0

  artisan:
    build:
      context: dockerfiles
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/laravel